In [1]:
import pandas as pd
dd1 = pd.read_csv('./bandgap-train/excel/train_dataGAP.csv')
dd1

        Gaps  Predictions
0   0.101441     0.138399
1   0.307010     0.261678
2   0.137167     0.121319
3  -0.510278    -0.438937
4   0.410156     0.478326
..       ...          ...
85 -0.086193     0.015539
86  0.570954     0.577827
87 -0.488469    -0.403622
88 -0.511569    -0.402224
89 -0.463025    -0.628428

[90 rows x 2 columns]

In [3]:
dd2 = pd.read_csv('./bandgap-train/excel/test_dataGAP.csv')
dd2

        Gaps  Predictions
0   0.108100     0.067917
1   0.449152     0.438417
2   0.107792     0.082427
3  -0.509400    -0.386880
4   0.118900     0.117522
5  -0.641844    -0.604036
6   0.499691     0.452625
7  -0.070733    -0.035111
8   0.098500     0.053938
9   0.157467     0.293022
10 -0.008533    -0.008021
11  0.337700     0.235035
12 -0.516425    -0.456564
13 -0.531078    -0.447009
14  0.276030     0.249120
15  0.117767     0.028506
16  0.211792     0.122346
17 -0.060208    -0.035152